### ISSUE TITLE
Preparation of data sets

### ISSUE THREAD

**Issue by JakubWojciechowski** [laughtervv/DepthAwareCNN#1]
Hello,
thanks a lot for sharing code. Could you provide methods that allow us to prepare datasets to run learning (lst and hha files)?
This will make it easier to reproduce the results. Thank you in advance.
Best regards.

**Comment by sabrinazuraimi** [comment]
Hi, running into a similar problem as I don't know how to prepare the lst and hha files. Did you manage to solve this?

**Comment by laughtervv** [comment]
Hi, I'm using scripts in this repo to prepare HHA. https://github.com/s-gupta/rcnn-depth/blob/ad56ddd57b0fe35b177d6dfe29b5e0601accbf18/rcnn/saveHHA.m

**Comment by sabrinazuraimi** [comment]
This might be a stupid question, but after downloading the labelled dataset from the NYUV2 dataset website, how do I prepare the lst file for training?

**Comment by JakubWojciechowski** [comment]
I adapted the code from [ZhangMenghe](https://github.com/ZhangMenghe/rgbd-processor-python) to SUNRGBD processing: [rgbd-processor-python](https://github.com/JakubWojciechowski/rgbd-processor-python). Just run demo.py

**Comment by sabrinazuraimi** [comment]
I can't seem to open an issue in that github repository that you gave but I'm getting an error in decoding the final 2d annotations

> ERROR decoding /home/muser/HDD/data/SUNRGBD/kv2/kinect2data/002922_2014-06-26_15-43-16_094959634447_rgbf000089-resize/annotation2Dfinal/index.json
> Traceback (most recent call last):
>   File "demo.py", line 251, in <module>
>     generate_targets(chooseSplit)
>   File "demo.py", line 222, in generate_targets
>     mask = generate_map(annotation_path, h, w)
>   File "demo.py", line 172, in generate_map
>     for poly in data['frames'][0]['polygon']:
> UnboundLocalError: local variable 'data' referenced before assignment
> 

When I checked, this is probably because it has an annotation called "propulsion""tool" which is not provided in the ans variable in demo.py??

**Comment by feipanir** [comment]
Anyone can share that how to process on NYUDv2 dataset?
Thanks a lot!

**Comment by renhaofan** [comment]
> Thanks! I got it working!

when I run demo.py, it raise a error, can you send me the lst and hha files please. My email is yqykrhf@163.com

**Comment by phoebe0920** [comment]
above methods could produce train/test list , but how can l get a val list? Looking for yours answer，thank you !

**Comment by xieyuhaoli** [comment]
> Thanks! I got it working!

Can you tell me how you made LST

**Comment by gunjan99** [comment]
> Thanks! I got it working!

Can you help with the camera intrinsic values that are needed in the code for the NYU dataset?
TIA

**Comment by fattyhu** [comment]
> Thanks! I got it working!

i meet the same problem, can you tell me how to solve it?

**Comment by fattyhu** [comment]
> Hi, I'm using scripts in this repo to prepare HHA. https://github.com/s-gupta/rcnn-depth/blob/ad56ddd57b0fe35b177d6dfe29b5e0601accbf18/rcnn/saveHHA.m

i am a student, i don`t know how to make lst. when i run train.sh i got error

Traceback (most recent call last):
  File "train.py", line 33, in <module>
    data_loader = CreateDataLoader(opt)
  File "/home/fattyhu/catkin_ws/DepthAwareCNN-master/data/data_loader.py", line 6, in CreateDataLoader
    data_loader.initialize(opt)
  File "/home/fattyhu/catkin_ws/DepthAwareCNN-master/data/custom_dataset_data_loader.py", line 51, in initialize
    self.dataset, self.dataset_val = CreateDataset(opt)
  File "/home/fattyhu/catkin_ws/DepthAwareCNN-master/data/custom_dataset_data_loader.py", line 40, in CreateDataset
    dataset.initialize(opt)
  File "/home/fattyhu/catkin_ws/DepthAwareCNN-master/data/nyuv2_dataset_crop.py", line 38, in initialize
    self.paths_dict = make_dataset_fromlst(opt.list)
  File "/home/fattyhu/catkin_ws/DepthAwareCNN-master/data/nyuv2_dataset_crop.py", line 23, in make_dataset_fromlst
    with open(listfilename) as f:
FileNotFoundError: [Errno 2] No such file or directory: './lists/train.lst'
can you tell me how to solve it?
