### ISSUE TITLE
fail compile depthconv

### ISSUE THREAD

**Issue by lixiang-ucas** [laughtervv/DepthAwareCNN#19]
Fails to compile the depthconv function. I'm using PyTorch 1.0.

**Comment by E18301194** [comment]
@lixiang-ucas I met the same problem as you. Have you solved it? thx

**Comment by gujiaqivadin** [comment]
> @lixiang-ucas I met the same problem as you. Have you solved it? thx

have you solved this problem~？ thanks you!
