### ISSUE TITLE
run sh make.sh

### ISSUE THREAD

**Issue by phoebe0920** [laughtervv/DepthAwareCNN#29]
excuse me. when l run sh make,sh  ,the following problem occurred.
`
depthavgpooling_cuda_kernel.cu(42): warning: variable "divcount" was declared but never referenced
          detected during instantiation of "void AvePoolForward_kernel<Dtype,Acctype>(int, const Dtype *, const Dtype *, int, int, int, int, int, int, int, int, int, int, int, Dtype *, Dtype *) [with Dtype=float, Acctype=double]" 
(65): here

Including CUDA code.
/home/pyq/segmentation/DepthAwareCNN/models/ops/depthavgpooling
Traceback (most recent call last):
  File "build.py", line 32, in <module>
    extra_objects=extra_objects
  File "/home/public/anaconda3/lib/python3.6/site-packages/setuptools/__init__.py", line 147, in __init__
    _Command.__init__(self, dist)
  File "/home/public/anaconda3/lib/python3.6/distutils/cmd.py", line 57, in __init__
    raise TypeError("dist must be a Distribution instance")
TypeError: dist must be a Distribution instance

`

 And then I tried to lower the version of setuptool, but it appeared
AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'

Can you give me some advice?Thanks.

**Comment by gujiaqivadin** [comment]
> excuse me. when l run sh make,sh ,the following problem occurred.
> `
> depthavgpooling_cuda_kernel.cu(42): warning: variable "divcount" was declared but never referenced
> detected during instantiation of "void AvePoolForward_kernel<Dtype,Acctype>(int, const Dtype *, const Dtype *, int, int, int, int, int, int, int, int, int, int, int, Dtype *, Dtype *) [with Dtype=float, Acctype=double]"
> (65): here
> 
> Including CUDA code.
> /home/pyq/segmentation/DepthAwareCNN/models/ops/depthavgpooling
> Traceback (most recent call last):
> File "build.py", line 32, in
> extra_objects=extra_objects
> File "/home/public/anaconda3/lib/python3.6/site-packages/setuptools/**init**.py", line 147, in **init**
> _Command.**init**(self, dist)
> File "/home/public/anaconda3/lib/python3.6/distutils/cmd.py", line 57, in **init**
> raise TypeError("dist must be a Distribution instance")
> TypeError: dist must be a Distribution instance
> 
> `
> 
> And then I tried to lower the version of setuptool, but it appeared
> AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'
> 
> Can you give me some advice?Thanks.

Have you solved this problem？ thanks a lot!
